[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
notify-debouncer-full = "0.5.0"
command-group = "5.0.1"
